# Generated by Django 5.2.8 on 2025-11-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(to='Blog.categoria', verbose_name='categoria'),
        ),
    ]
